# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop, 'project/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16.x", "18.x"]
        solana: ["1.10.34"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          solana_version: ${{ matrix.solana }}
          
      - name: Run Tests
        run: ./gradlew test
