name: Publish package to GitHub Packages
on:
  release:
    types: [push]

jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        run: gradle clean assemble publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}